<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class PendaftaranPilihan extends Model
{
    use HasFactory, HasUuids;

    protected $table = 'pendaftaran_pilihan';
    public $timestamps = false; // Karena hanya ada tanggal_submit yang auto-generated by DB (timestamp)

    protected $fillable = [
        'id',
        'siswa_id',
        'periode_pendaftaran_id',
        'tanggal_submit',
    ];

    protected $casts = [
        'tanggal_submit' => 'datetime',
    ];

    public function siswa(): BelongsTo
    {
        return $this->belongsTo(Siswa::class);
    }

    public function periodePendaftaran(): BelongsTo
    {
        return $this->belongsTo(PeriodePendaftaran::class);
    }

    public function detailPendaftaran(): HasMany
    {
        return $this->hasMany(DetailPendaftaranPilihan::class, 'pendaftaran_pilihan_id')->orderBy('urutan_pilihan', 'asc');
    }
}
